name: Update Server Hashes
on:
  push:
    branches: [ main ] # Triggers on updates to the main branch

jobs:
  send-command:
    runs-on: ubuntu-latest
    steps:
      - name: Send Proxy RCON Command
        uses: Plagiatus/RCON-Action@v0.3
        with:
          server: ${{ secrets.PROXY_HOST }}      # Pulls from org secret
          port: ${{ secrets.PROXY_RCON_PORT }}        # Pulls from org secret
          password: ${{ secrets.RCON_PASSWORD }}  # Pulls from org secret
          send-push-info: false
          commands: '["frp generatehashes"]'
          
          
      - name: Send Creative RCON Command
        uses: Plagiatus/RCON-Action@v0.3
        with:
          server: ${{ secrets.CREATIVE_HOST }}      # Pulls from org secret
          port: ${{ secrets.CREATIVE_RCON_PORT }}        # Pulls from org secret
          password: ${{ secrets.RCON_PASSWORD }}  # Pulls from org secret
          send-push-info: false
          commands: '["frp generatehashes"]'
