name: Update Server Hashes
on:
  workflow_run:
    workflows: ["Create Archive"] # Must match the 'name' in your other file
    types:
      - completed # Triggers when the other workflow finishes

jobs:
  send-command:
    runs-on: ubuntu-latest
    steps:
      - name: Send Proxy RCON Command
        uses: Plagiatus/RCON-Action@v0.3
        with:
          server: ${{ secrets.PROXY_HOST }}      # Pulls from org secret
          port: ${{ secrets.PROXY_RCON_PORT }}        # Pulls from org secret
          password: ${{ secrets.RCON_PASSWORD }}  # Pulls from org secret
          send-push-info: false
          commands: '["frp generatehashes"]'
          
          
      - name: Send Creative RCON Command
        uses: Plagiatus/RCON-Action@v0.3
        with:
          server: ${{ secrets.CREATIVE_HOST }}      # Pulls from org secret
          port: ${{ secrets.CREATIVE_RCON_PORT }}        # Pulls from org secret
          password: ${{ secrets.RCON_PASSWORD }}  # Pulls from org secret
          send-push-info: false
          commands: '["frp generatehashes"]'
